spring:
  datasource:
    name: user
    url: jdbc:mysql://${datasource.ip_port}/plancoin_exchange_dev
    username: ${datasource.username}
    password: ${datasource.password}
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

# redis 配置
  redis:
    database: 8
    host: 47.98.134.140
    port: 6379
    pool:
      max-idle: 30
      max-active: 600
      max-wait: 10000
    password: 123
    timeout: 60000  # 连接超时时长（毫秒）

# rocketmq 配置
  rocketmq:
    nameServer: 47.98.134.140:9876
    producer-group-name: apiGroup

# rabbitmq配置
  rabbitmq:
    host: 47.98.134.140
    port: 5672
    username: admin
    password: admin
    publisher-confirms: true
    virtual-host: /
#    addresses: 192.168.2.252:5672,192.168.2.253:5672
mybatis:
    typeAliasesPackage: com.lianhui.user.model
    mapperLocations: classpath:mybatis/*.xml