spring:
  datasource:
    name: user
    url: jdbc:mysql://${datasource.ip_port}/plancoin_exchange_dev
    username: ${datasource.username}
    password: ${datasource.password}
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

# redis 配置
  redis:
    database: 8
    host: 47.98.134.140
    port: 6379
    pool:
      max-idle: 30
      max-active: 600
      max-wait: 10000
    password: renfei
    timeout: 60000  # 连接超时时长（毫秒）

# rocketmq 配置
  rocketmq:
    name-server-address: 47.98.134.140:9876
    # 可选, 如果无需发送消息则忽略该配置
    producer-group: local_pufang_producer
    # 发送超时配置毫秒数, 可选, 默认3000
    send-msg-timeout: 5000
    # 追溯消息具体消费情况的开关，默认打开
    #trace-enabled: false
    # 是否启用VIP通道，默认打开
    vip-channel-enabled: false

# rabbitmq配置
#  rabbitmq:
#    host: 47.98.134.140
#    port: 5672
#    username: admin
#    password: admin
#    publisher-confirms: true
#    virtual-host: /
#    addresses: 192.168.2.252:5672,192.168.2.253:5672
feign:
   hystrix:
     enabled: true
mybatis:
    typeAliasesPackage: com.lianhui.user.model
    mapperLocations: classpath:mybatis/*.xml