server:
  port: 8761
spring:
  profiles:
    active: dev
  application:
    name: eureka      
---
server:
  port: 8761
spring:
  profiles: dev
  application:
    name: eureka
eureka:
  server:
    enable-self-preservation: false #关闭自启动
  datacenter: cloud
  environment: dev #开发环境的注解
  client:
    register-with-eureka: false #表示是否注册自身到eureka服务器
    fetch-registry: false #表示是否从eureka服务器获取注册信息
    service-url:
      defaultZone: http://localhost:8761/eureka
---
spring:
  profiles: test
  application:
    name: eureka2
server:
  port: 8762
eureka:
  server:
    enable-self-preservation: false #关闭自启动
  datacenter: cloud
  environment: test #开发环境的注解
  client:
    register-with-eureka: false #表示是否注册自身到eureka服务器
    fetch-registry: false #表示是否从eureka服务器获取注册信息
    service-url:
      defaultZone: http://localhost:8762/eureka
---
spring:
  profiles: prd
  application:
    name: eureka
server:
  port: 8762
eureka:
  server:
    enable-self-preservation: false #关闭自启动
  datacenter: cloud
  environment: prd #开发环境的注解
  client:
    register-with-eureka: false #表示是否注册自身到eureka服务器
    fetch-registry: false #表示是否从eureka服务器获取注册信息
    service-url:
      defaultZone: http://localhost:8762/eureka
  
